version: '3.5'
services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbt"
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Run `make .env` to set $USER_ID and $GROUP_ID
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: "/root/.virtualenvs/dbt/bin/pytest"
    env_file:
      - ./test.env
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    depends_on:
      - database

networks:
  default:
    name: dbt-net
