[package]
name = "runner"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
itertools = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0.26"
