version: 2.1
jobs:
  unit:
    docker: &test_only
      - image: fishtownanalytics/test-container:12
        environment:
          DBT_INVOCATION_ENV: circle
          DOCKER_TEST_DATABASE_HOST: "database"
          TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - checkout
      - run: tox -p -e py36,py37,py38
  lint:
    docker: *test_only
    steps:
      - checkout
      - run: tox -e mypy,flake8 -- -v
  build-wheels:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Build wheels
          command: |
            python3.8 -m venv "${PYTHON_ENV}"
            export PYTHON_BIN="${PYTHON_ENV}/bin/python"
            $PYTHON_BIN -m pip install -U pip setuptools
            $PYTHON_BIN -m pip install -r requirements.txt
            $PYTHON_BIN -m pip install -r dev-requirements.txt
            /bin/bash ./scripts/build-wheels.sh
            $PYTHON_BIN ./scripts/collect-dbt-contexts.py > ./dist/context_metadata.json
            $PYTHON_BIN ./scripts/collect-artifact-schema.py > ./dist/artifact_schemas.json
          environment:
            PYTHON_ENV: /home/tox/build_venv/
      - store_artifacts:
          path: ./dist
          destination: dist
  integration-postgres:
    docker:
      - image: fishtownanalytics/test-container:12
        environment:
          DBT_INVOCATION_ENV: circle
          DOCKER_TEST_DATABASE_HOST: "database"
          TOX_PARALLEL_NO_SPINNER: 1
      - image: postgres
        name: database
        environment:
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dbt"
    steps:
      - checkout
      - run:
          name: Setup postgres
          command: bash test/setup_db.sh
          environment:
            PGHOST: database
            PGUSER: root
            PGPASSWORD: password
            PGDATABASE: postgres
      - run:
          name: Postgres integration tests
          command: tox -p -e py36-postgres,py38-postgres -- -v -n4
          no_output_timeout: 30m
      - store_artifacts:
          path: ./logs
  integration-snowflake:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Snowflake integration tests
          command: tox -p -e py36-snowflake,py38-snowflake -- -v -n4
          no_output_timeout: 30m
      - store_artifacts:
          path: ./logs
  integration-redshift:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Redshift integration tests
          command: tox -p -e py36-redshift,py38-redshift -- -v -n4
          no_output_timeout: 30m
      - store_artifacts:
          path: ./logs
  integration-bigquery:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Bigquery integration test
          command: tox -p -e py36-bigquery,py38-bigquery -- -v -n4
          no_output_timeout: 30m
      - store_artifacts:
          path: ./logs

workflows:
  version: 2
  test-everything:
    jobs:
      - lint
      - unit
      - integration-postgres:
          requires:
            - unit
      - integration-redshift:
          requires:
            - unit
      - integration-bigquery:
          requires:
            - unit
      - integration-snowflake:
          requires:
            - unit
      - build-wheels:
          requires:
            - lint
            - unit
            - integration-postgres
            - integration-redshift
            - integration-bigquery
            - integration-snowflake
