version: 2
jobs:
  unit:
    docker: &containers
      - image: fishtownjacob/test-container
      - image: postgres
        name: database
        environment: &pgenv
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dbt"
    steps:
      - checkout
      - run: &setupdb
          name: Setup postgres
          command: bash test/setup_db.sh
          environment:
            PGHOST: database
            PGUSER: root
            PGPASSWORD: password
            PGDATABASE: postgres
      - run: tox -e pep8,unit-py27,unit-py36
  integration-postgres-py36:
    docker: *containers
    steps:
      - checkout
      - run: *setupdb
      - run:
          name: Run tests
          command: tox -e integration-postgres-py36
  integration-snowflake-py36:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-snowflake-py36
          no_output_timeout: 1h
  integration-redshift-py36:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-redshift-py36
  integration-bigquery-py36:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-bigquery-py36
  integration-postgres-py27:
    docker: *containers
    steps:
      - checkout
      - run: *setupdb
      - run:
          name: Run tests
          command: tox -e integration-postgres-py27
  integration-snowflake-py27:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-snowflake-py27
          no_output_timeout: 1h
  integration-redshift-py27:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-redshift-py27
  integration-bigquery-py27:
    docker: *containers
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-bigquery-py27

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      - integration-postgres-py36:
          requires:
            - unit
      - integration-postgres-py27:
          requires:
            - unit
      - integration-redshift-py27:
          requires:
            - integration-postgres-py27
      - integration-bigquery-py27:
          requires:
            - integration-postgres-py27
      - integration-snowflake-py27:
          requires:
            - integration-postgres-py27
      - integration-redshift-py36:
          requires:
            - integration-postgres-py36
      - integration-bigquery-py36:
          requires:
            - integration-postgres-py36
      - integration-snowflake-py36:
          requires:
            - integration-postgres-py36
