version: 2
jobs:
  unit:
    docker: &test_and_postgres
      - image: fishtownjacob/test-container
      - image: postgres
        name: database
        environment: &pgenv
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dbt"
    steps:
      - checkout
      - run: &setupdb
          name: Setup postgres
          command: bash test/setup_db.sh
          environment:
            PGHOST: database
            PGUSER: root
            PGPASSWORD: password
            PGDATABASE: postgres
      - run: tox -e flake8,unit-py36
  integration-postgres-py36:
    docker: *test_and_postgres
    steps:
      - checkout
      - run: *setupdb
      - run:
          name: Run tests
          command: tox -e integration-postgres-py36
      - store_artifacts:
          path: ./logs
  integration-snowflake-py36:
    docker: &test_only
      - image: fishtownjacob/test-container
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-snowflake-py36
          no_output_timeout: 1h
      - store_artifacts:
          path: ./logs
  integration-redshift-py36:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-redshift-py36
      - store_artifacts:
          path: ./logs
  integration-bigquery-py36:
    docker: *test_only
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -e integration-bigquery-py36
      - store_artifacts:
          path: ./logs

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      - integration-postgres-py36:
          requires:
            - unit
      - integration-redshift-py36:
          requires:
            - integration-postgres-py36
      - integration-bigquery-py36:
          requires:
            - integration-postgres-py36
      - integration-snowflake-py36:
          requires:
            - integration-postgres-py36
