# This is a workflow to run our integration tests for windows and mac

name: dbt Tests

# Triggers
on:
  # Triggers the workflow on push or pull request events and also adds a manual trigger
  push:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'releases/*'
  pull_request:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'pr/*'
      - 'releases/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PostgresIntegrationTest:
    runs-on: 'windows-latest' #TODO: Add Mac support
    environment: 'Postgres'
    steps:
    - uses: actions/checkout@v2
    - name: 'Install postgresql and set up database'
      shell: pwsh
      run: |
          $serviceName = Get-Service -Name postgresql*
          Set-Service -InputObject $serviceName -StartupType Automatic
          Start-Service -InputObject $serviceName
          & $env:PGBIN\createdb.exe -U postgres dbt
          & $env:PGBIN\psql.exe  -U postgres -c "CREATE ROLE root WITH PASSWORD '$env:ROOT_PASSWORD';"
          & $env:PGBIN\psql.exe  -U postgres -c "ALTER ROLE root WITH LOGIN;"
          & $env:PGBIN\psql.exe  -U postgres -c "GRANT CREATE, CONNECT ON DATABASE dbt TO root WITH GRANT OPTION;"
          & $env:PGBIN\psql.exe  -U postgres -c "CREATE ROLE noaccess WITH PASSWORD '$env:NOACCESS_PASSWORD' NOSUPERUSER;"
          & $env:PGBIN\psql.exe  -U postgres -c "ALTER ROLE noaccess WITH LOGIN;"
          & $env:PGBIN\psql.exe  -U postgres -c "GRANT CONNECT ON DATABASE dbt TO noaccess;"
      env:
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          NOACCESS_PASSWORD: ${{ secrets.NOACCESS_PASSWORD }}
      
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.7'
        architecture: 'x64'
        
    - name: 'Install dependencies'
      run: python -m pip install --upgrade pip && pip install tox
      
    - name: 'Run integration tests'
      run: python -m tox -e py-postgres -- -v -n4
      
  # These three are all similar except secure environment variables, which MUST be passed along to their tasks,
  # but there's probably a better way to do this!
  SnowflakeIntegrationTest:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: 'Snowflake'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip && pip install tox

      - name: 'Run integration tests'
        run: python -m tox -e py-snowflake -- -v -n4
        env:
          SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
          SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
          SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
          SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
          SNOWFLAKE_TEST_OAUTH_REFRESH_TOKEN: ${{ secrets.SNOWFLAKE_TEST_OAUTH_REFRESH_TOKEN }}
          SNOWFLAKE_TEST_OAUTH_CLIENT_ID: ${{ secrets.SNOWFLAKE_TEST_OAUTH_CLIENT_ID }}
          SNOWFLAKE_TEST_OAUTH_CLIENT_SECRET: ${{ secrets.SNOWFLAKE_TEST_OAUTH_CLIENT_SECRET }}
          SNOWFLAKE_TEST_ALT_DATABASE: ${{ secrets.SNOWFLAKE_TEST_ALT_DATABASE }}
          SNOWFLAKE_TEST_ALT_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_ALT_WAREHOUSE }}
          SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
          SNOWFLAKE_TEST_QUOTED_DATABASE: ${{ secrets.SNOWFLAKE_TEST_QUOTED_DATABASE }}
          SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}

  BigQueryIntegrationTest:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: 'Bigquery'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7'
          architecture: 'x64'
        
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip && pip install tox
      
      - name: 'Run integration tests'
        run: python -m tox -e py-bigquery -- -v -n4
        env:
          BIGQUERY_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_JSON }}
          BIGQUERY_TEST_ALT_DATABASE: ${{ secrets.BIGQUERY_TEST_ALT_DATABASE }}

  RedshiftIntegrationTest:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: 'Redshift'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip && pip install tox

      - name: 'Run integration tests' 
        run: python -m tox -e py-redshift -- -v -n4
        env:
          REDSHIFT_TEST_DBNAME: ${{ secrets.REDSHIFT_TEST_DBNAME }}
          REDSHIFT_TEST_PASS: ${{ secrets.REDSHIFT_TEST_PASS }}
          REDSHIFT_TEST_USER: ${{ secrets.REDSHIFT_TEST_USER }}
          REDSHIFT_TEST_PORT: ${{ secrets.REDSHIFT_TEST_PORT }}
          REDSHIFT_TEST_HOST: ${{ secrets.REDSHIFT_TEST_HOST }}
